### ISSUE TITLE
Unsupported item key.

### ISSUE THREAD

**Issue by pavkamlc** [milzulempis/Zabbix-Wordpress-Template#2]
On my Zabbix 5.2.3 plugin write error "Unsupported item key.".
In discovery rule key is "file.discovery[/var/www,XndwLWNvbmZpZy5waHAk]", but in zabbix documentation isn't published file.discovery.
On agent machine I test this:
`./discover_files.py /var/www/ XndwLWNvbmZpZy5waHAk`
and this works.

**Comment by milzulempis** [comment]
This means, that zabbix don't know what is "file.dicovery" key.
Did you copied userparameter_wp.config? Also restart of zabbix agent is needed.

**Comment by pavkamlc** [comment]
You've right, zabbix don't know this.
I found why. Default agent configuration use include:
_Include=/etc/zabbix/zabbix_agentd.d/*.conf_
But your file is named config, this is the problem. After rename, problem is solved.

Then I found another problem with rights. Agent must have permission into directory, so I need:
usermod zabbix -a -G apache

And now it works. Can you rename file in git and add note about permission into README?

**Comment by milzulempis** [comment]
Done.
